### ISSUE TITLE
Support for Glyphs3

### ISSUE THREAD

**Issue by adrianzwz** [danielgamage/SelectionPalette#10]
Hi, I've been using this plugin quite a lot since Glyphs2 (useful for designing complex CJK fonts)
wonder if there are any plans for supporting Glyphs3?

Thanks in advance!

**Comment by danielgamage** [comment]
i haven't had a chance to look at the updated API in 3, but i would also like it to be working there! i'll keep it in mind if i get some free time

**Comment by Mark2Mark** [comment]
I have a ported version that works in Glyphs 3 now. Would you consider taking a pull request, preferably into a new Glyphs 3 branch from me?

**Comment by danielgamage** [comment]
Hi @Mark2Mark, I appreciate that you took the time to work on porting! I did end up rewriting the plugin with the Python API + Vanilla, but I've added some new features and touched up the UI since I haven't updated it in so long. Because of that, I wouldn't want you to put too much extra time into working on a separate version, but I would love to take a look at your PR anyways if you'd like to share. I'm sure I can learn a thing (or 5) from you :)

There are a couple of issues I've detailed in #11 that I'll be working out before pushing the update, but I can write you in as a co-auther where applicable if you post your PR

**Comment by Mark2Mark** [comment]
Hi Daniel,
Sure, I am happy to push then. Could make a branch that is just for reference. Unfortunately there won’t be much to learn from. I basically just changed the linked framework, the iteration over `paths` is now `shapes` and some tiny touches. Didn't touch/change or even read the entire code :) 

Curious about your new version though. I used the plugin a lot to select anchors mostly back then. Thanks for making it.

**Comment by clauseggers** [comment]
Hey guys, what’s the status on a v3 compatible version?

**Comment by danielgamage** [comment]
should be in the plugin manager now! 

via https://github.com/schriftgestalt/glyphs-packages/pull/135
